### ISSUE TITLE
ImportError: cannot import name 'compose'

### ISSUE THREAD

**Issue by ghost** [PiSimo/PiCamNN#4]
Hello! Judging by the description, an excellent project! But I can not start it.
`user@user-MS-7865:~/PiCamNN-master$ sudo python3 picam.py`
`[sudo] пароль для user: `
`Using TensorFlow backend.`
`Traceback (most recent call last):`
`  File "picam.py", line 12, in <module>`
`    from yad2k.models.keras_yolo import yolo_eval, yolo_head`
`  File "/home/user/PiCamNN-master/yad2k/models/keras_yolo.py", line 10, in <module>`
`    from ..utils import compose`
`ImportError: cannot import name 'compose'`

**Comment by Ruslan1990** [comment]
Files from the folder yad2k replaced with https://github.com/allanzelener/YAD2K/tree/master/yad2k.
 An error `compose` has occurred, but a new one has appeared. A motion detector is being issued, but recognition does not occur.
`user@user-MS-7865:~/PiCamNN-master$ sudo python3 picam.py`
`Using TensorFlow backend.`
`Starting PiCam....`
`[PiCam] Height:480 | Width:640`
`[PiCamNN] Updating file...`
`[PiCamNN] File has been update yet !`
`[PiCam] Loading old video File...loaded!`
`[PiCam] Starting Yolo Thread....`
`[PiCam] Starting main loop...`
`2018-01-03 13:54:15.399236: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports`
`instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX`
`2018-01-03 13:54:15.857334: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful` `NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so` `returning NUMA node zero`
`2018-01-03 13:54:15.857955: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0` `with properties: `
`name: GeForce GT 630 major: 3 minor: 5 memoryClockRate(GHz): 0.9015`
`pciBusID: 0000:01:00.0`
`totalMemory: 979.81MiB freeMemory: 701.69MiB`
`2018-01-03 13:54:15.858006: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating` `TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GT 630, pci bus id: 0000:01:00.0,` `compute capability: 3.5)`
`[PiCam] Loading anchors file..`.
`[PiCam] Loading yolo model (/home/pi/PiCamNN/tiny.h5)...`
`Exception in thread Thread-1:`
`Traceback (most recent call last):`
  `File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner`
   ` self.run()`
 ` File "/usr/lib/python3.5/threading.py", line 862, in run`
    `self._target(*self._args, **self._kwargs)`
  `File "picam.py", line 118, in yoloThread`
    `yolo_model = load_model(model_path)  #Loading Tiny YOLO`
  `File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 205, in load_model`
    `raise ImportError('`load_model` requires h5py.')`
`ImportError: `load_model` requires h5py.`

`[PiCam] Movement (13:54:46)`
`[PiCam] Movement (13:54:46)`
`[PiCam] Movement (13:54:46)`
`[PiCam] Movement (13:54:46)`

**Comment by Ruslan1990** [comment]
Files from the folder yad2k replaced with https://github.com/allanzelener/YAD2K/tree/master/yad2k.
An error compose has occurred, but a new one has appeared. A motion detector is being issued, but recognition does not occur.

user@user-MS-7865:~/PiCamNN-master$ sudo python3 picam.py
Using TensorFlow backend.
Starting PiCam....
[PiCam] Height:480 | Width:640
[PiCamNN] Updating file...
[PiCamNN] File has been update yet !
[PiCam] Loading old video File...loaded!
[PiCam] Starting Yolo Thread....
[PiCam] Starting main loop...
2018-01-03 14:11:00.891732: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
[PiCam] Movement (14:11:00)
[PiCam] Movement (14:11:00)
2018-01-03 14:11:01.059157: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-01-03 14:11:01.059723: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GT 630 major: 3 minor: 5 memoryClockRate(GHz): 0.9015
pciBusID: 0000:01:00.0
totalMemory: 979.81MiB freeMemory: 701.44MiB
2018-01-03 14:11:01.059766: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GT 630, pci bus id: 0000:01:00.0, compute capability: 3.5)
[PiCam] Loading anchors file...
[PiCam] Loading yolo model (/home/user/PiCamNN-master/tiny.h5)...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "picam.py", line 118, in yoloThread
    yolo_model = load_model(model_path)  #Loading Tiny YOLO
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 205, in load_model
    raise ImportError('`load_model` requires h5py.')
ImportError: `load_model` requires h5py.

[PiCam] Movement (14:11:07)
[PiCam] Movement (14:11:07)
[PiCam] Movement (14:11:07)
[PiCam] Movement (14:11:08)
[PiCam] Movement (14:11:08)

**Comment by PiSimo** [comment]
Hi __Ruslan1990__ ,

for a quick fix you could just paste the utils.py code into the keras_yolo.py and keras_darknet19.py files and remove the imports , or move the utils.py to the models folder and modify the import (removing the two dots, in both files).

I hope this will work.
