### ISSUE TITLE
ImportError: cannot import name 'compose'

### ISSUE THREAD

**Issue by rahulkrishnan98** [PiSimo/PiCamNN#8]
> File "/home/pi/PiCamNN/yad2k/models/keras_yolo.py", line 10, in <module>
    from ..utils import compose

while trying to run the script above mentioned file raises the error. Is there any-workaround for this presently.

**System Configuration**
Model: Raspberry Pi3 B
OS: Raspbian Stretch 
Memory: 32Gb Card

**Comment by PiSimo** [comment]
Try this: https://github.com/PiSimo/PiCamNN/issues/4
